DROP DATABASE IF EXISTS distribuidos;
CREATE DATABASE distribuidos;
USE distribuidos;

CREATE TABLE `noticias` (
    id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
    titulo TEXT NOT NULL,
    subtitulo TEXT,
    articulo TEXT NOT NULL,
    contador INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL  DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
AUTO_INCREMENT=1 ;