#!/bin/bash
install() {
  if [ -x "$(command -v $1)" ]; then
    echo -e "\e[4mYa tiene instalado $1\e[0m"
  else
    echo -e "\e[4mInstalando $1\e[0m"
    apt-get install $1 -y
  fi
}

# git install 
# make install
# gcc install
# install wget, unzip, mysql-server
# redis install http://download.redis.io/releases/redis-4.0.6.tar.gz

# dataset
wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
unzip bbc-fulltext.zip
rm bbc-fulltext.zip
mv bbc dataset

# redis
wget http://download.redis.io/releases/redis-4.0.6.tar.gz
tar -zxvf redis-4.0.6.tar.gz
rm redis-4.0.6.tar.gz
mv redis-4.0.6 .redis
cd .redis
make
src/redis-server --daemonize yes
cd ..

# thrift
wget http://www-us.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz
tar -zxvf thrift-0.11.0.tar.gz
rm thrift-0.11.0.tar.gz
mv thrift-0.11.0 .thrift
cd .thrift
# dependencias thrift

sudo apt-get install automake bison flex g++ git libboost-all-dev libevent-dev libssl-dev libtool make pkg-config
./bootstrap.sh
./configure
make
make check
cd .thrift/lib/py
sudo python setup.py install