#!/bin/bash
# nvm

# echo 'export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm' > ~/.profile

# install dependencias python
pip install < requirements.txt 

# install nginx config file
cp cache.nginx /etc/nginx/sites-enabled
service nginx restart