#!/bin/bash
install() {
  if [ -x "$(command -v $1)" ]; then
    echo -e "\e[4mYa tiene instalado $1\e[0m"
  else
    echo -e "\e[4mInstalando $1\e[0m"
    apt-get install $1 -y
  fi
}

# git install 
# install wget, unzip, mysql-server
# redis install http://download.redis.io/releases/redis-4.0.6.tar.gz

wget http://mlg.ucd.ie/files/datasets/bbc-fulltext.zip
unzip bbc-fulltext.zip
mv bbc dataset